apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    backstage.io/managed-by-location: file:C:\Users\Ahsan Aslam\Downloads\Backstage\one\examples\entities.yaml
    backstage.io/managed-by-origin-location: file:C:\Users\Ahsan Aslam\Downloads\Backstage\one\examples\entities.yaml
  name: backstage-component-test
  uid: 36edc60c-32e2-448c-bb86-5e236cd59f03
  etag: b75ba784d243cb4e2443c6bafae8f1e83379e1fb
relations:
  - type: ownedBy
    targetRef: group:default/guests
    target:
      kind: group
      namespace: default
      name: guests
  - type: partOf
    targetRef: system:default/examples
    target:
      kind: system
      namespace: default
      name: examples
  - type: providesApi
    targetRef: api:default/example-grpc-api
    target:
      kind: api
      namespace: default
      name: example-grpc-api
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis:
    - example-grpc-api
